/*
 * NewJFrame.java
 *
 * Created on 20 de Fevereiro de 2006, 15:55
 */

package org.bandarra.jmapper;
import java.io.*;
import org.bandarra.map.*;
import org.bandarra.tabulacao.*;
import java.awt.*;

/**
 *
 * @author  andre.bandarra
 */
class MapPanel extends javax.swing.JPanel{
    MapDrawer map = new SimpleMapDrawer();
    public void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g); 
        try{
            FileInputStream fisTab = new FileInputStream("c:\\Andre\\JavaSrc\\JMapper\\\\etc\\dd_es.tab");
            BufferedReader bfTab = new BufferedReader(new InputStreamReader(fisTab));
            TabWinReader twr = new TabWinReader(bfTab);
            TabData td = twr.getTabData();
            TabDataColorChooser tdcc = new TabDataColorChooser(td);        
            RangesDrawer rg = new RangesDrawer(tdcc);
            rg.setSize(new Rectangle(0,0,this.getWidth(),this.getHeight()));
            rg.draw(g);
        } catch (IOException ioe){
            ioe.printStackTrace();
        }
    }
}
public class NewJFrame extends javax.swing.JFrame {
    
    /** Creates new form NewJFrame */
    public NewJFrame() {
        MapPanel mp = new MapPanel();
        this.getContentPane().add(mp);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
